export { default as login } from './login.controller'
export { default as register } from './register.controller'
export { default as logout } from './logout.controller'
export { default as google } from './google.controller'
export { default as facebook } from './facebook.controller'
